# Site settings
name: About Blank
email: joe-ji@outlook.com
author: Joe Ji
url: http://www.joeji.org
resume_site: 
github: https://github.com/joe-ji
baseurl: 
description: Just for fun.:P
meta_description: blog,个人博客;
motto: 
banner: 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: joe-ji@outlook.com
highlighter: Pygments

# Build settings
markdown: kramdown

